name: pull_request test
on:
  pull_request:
    types:
      - labeled
      - unlabeled
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        echo "Ref: $GITHUB_REF"
        echo "Sha: $GITHUB_SHA"
    - run: ls
    - run: cat $GITHUB_EVENT_PATH
